kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APPNAVN }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: PDL_URL
      value: {{ PDL_URL }}
    - name: DOKSIKKERHETSNETT_FINNMOTTATTEJOURNALPOSTERURL
      value: {{ DOKSIKKERHETSNETT_FINNMOTTATTEJOURNALPOSTERURL }}
    - name: DOKSIKKERHETSNETT_SECURITYSERVICETOKENURL
      value: {{ DOKSIKKERHETSNETT_SECURITYSERVICETOKENURL }}
    - name: DOKSIKKERHETSNETT_OPPGAVEURL
      value: {{ DOKSIKKERHETSNETT_OPPGAVEURL }}
    - name: DOKSIKKERHETSNETT_OPPRETTJIRAISSUEURL
      value: {{ DOKSIKKERHETSNETT_OPPRETTJIRAISSUEURL }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1500m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
      - kvPath: {{ SRVDOKSIKKERHETSNETT }}
        mountPath: /var/run/secrets/nais.io/srvdoksikkerhetsnt