kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{ APPNAVN }}
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
spec:
  env:
    - name: JAVA_TRUSTSTORE_OPTIONS
      value: "-Djavax.net.ssl.trustStore=$(NAV_TRUSTSTORE_PATH)
              -Djavax.net.ssl.trustStorePassword=$(NAV_TRUSTSTORE_PASSWORD)"
    - name: JDK_JAVA_OPTIONS
      value: "-XX:MaxRAMPercentage=75
              $(JAVA_PROXY_OPTIONS) $(JAVA_TRUSTSTORE_OPTIONS)"
    - name: DOKSIKKERHETSNETT_ENDPOINTS_JIRA
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_JIRA }}
    - name: DOKSIKKERHETSNETT_ENDPOINTS_OPPGAVE_URL
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_OPPGAVE_URL }}
    - name: DOKSIKKERHETSNETT_ENDPOINTS_OPPGAVE_SCOPE
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_OPPGAVE_SCOPE }}
    - name: DOKSIKKERHETSNETT_ENDPOINTS_DOKARKIV_URL
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_DOKARKIV_URL }}
    - name: DOKSIKKERHETSNETT_ENDPOINTS_DOKARKIV_SCOPE
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_DOKARKIV_SCOPE }}
    - name: DOKSIKKERHETSNETT_ENDPOINTS_PDL_URL
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_PDL_URL }}
    - name: DOKSIKKERHETSNETT_ENDPOINTS_PDL_SCOPE
      value: {{ DOKSIKKERHETSNETT_ENDPOINTS_PDL_SCOPE }}
  image: {{ image }}
  ingresses:
    {{#each INGRESSES}}
       - {{this }}
      {{/each}}
  liveness:
    path: /actuator/health/liveness
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: /actuator/health/readiness
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    requests:
      cpu: 10m
      memory: 512Mi
    limits:
      memory: 1024Mi
  azure:
    application:
      enabled: true
  webproxy: true
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  envFrom:
    - secret: slack-alerts
    - secret: jira-service-user